### ISSUE TITLE
x icon missing

### ISSUE THREAD

**Issue by xkeshav** [natemoo-re/astro-icon#170]
### What version of `astro-icon` are you using?

0.8.0

### Astro Info

```block
please add x icon ( formerly twitter)
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

x icon missing

### What's the expected result?

x icon should present

### Link to Minimal Reproducible Example

N/A

**Comment by Pukimaa** [comment]
This does depend on the Icon set you use (Iconify icons are built-in). However since packages were outdate prior to v1, a lot of icons were broken as well and wouldn't work.

**Comment by natemoo-re** [comment]
Please follow the required template when filing an issue.

I am no longer supporting the remote icon service that powered `astro-icon` prior to v1 as it was too much of a maintenance burden to keep it updated with constant changes to the icons themselves. Icons in v1 are installed on your local machine so that you can upgrade packages at your own convenience.
