### ISSUE TITLE
"Unable to locate X icon!" without restarting dev server

### ISSUE THREAD

**Issue by bholmesdev** [natemoo-re/astro-icon#207]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v3.2.3
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/markdoc
                         @astrojs/tailwind
                         astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When adding a new entry to the `icons/` directory, I see an "unable to locate X icon!" error. Restarting the dev server resolves the issue. Strangely, this does not occur on initial installation or for the first icon added to `icons/`. However, after restarting the dev server once and adding more additions to `icons/`, the error appears.

See stackblitz example below. Try copying a `.svg` entry under a new name and update the Icon in `pages/index.astro` to reference it.

<img width="1186" alt="image" src="https://github.com/natemoo-re/astro-icon/assets/51384119/5aeccb22-4674-46fe-8408-6b244c2d7eac">

### What's the expected result?

Updates to `icons/` are detected while the dev server is running.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/edit/github-ds52xs

**Comment by felixzrte** [comment]
I can't get it to work even if I restart the dev server

**Comment by natemoo-re** [comment]
Hmm, very odd. Thanks for the repro! I'll try to figure out what's going on here. Might need to add an explicit watcher for the `icons/` directory in the Vite plugin so we can rebuild the virtual module when that's needed.

**Comment by hkbertoson** [comment]
Not sure if this is related but seems to be. But if I update my Astro Config to have a new icon. I have to restart the dev server for it to pick up that a new one is there. Otherwise, it says that it does not exist. 

Start the page and then in the config. Add a new icon and try to use it. 

https://stackblitz.com/edit/withastro-astro-qh7fcg

**Comment by faizananwerali** [comment]
+1

Same thing happend to me, had to restart dev server everytime

**Comment by anridev24** [comment]
+1

**Comment by AhmedHamedd2017** [comment]
+1

**Comment by cotton123236** [comment]
+1

Same problem, v0.8.3 is working fine! But it seems no longer support the latest version of Astro.

**Comment by cotton123236** [comment]
It seems to be caused by here.
https://github.com/natemoo-re/astro-icon/blob/a4ff8736965214e16ce0b72364f43b3a4973f281/packages/core/src/vite-plugin-astro-icon.ts#L33

The icons only be loaded when vite server start, maybe you can add a `fs.watch` to watch icons dir or any other smarter way to update `collections["local"]`.

Thanks for this great integration by the way.

**Comment by bitsmakerde** [comment]
I get the same error. I can't use it.

**Comment by carlkentor** [comment]
Same issue ;(

**Comment by ToqYang** [comment]
Same issue v1.1.1 but i tried to restart and it doesnt work

https://github.com/easy-post-ia-1/easy-post-ia-landing/tree/KAN-18-Home
Commit: 689f75c8fe9ca79612e33be71a32082a60444813

<img width="1440" alt="Screenshot 2024-09-25 at 6 07 52 PM" src="https://github.com/user-attachments/assets/4d38391b-d243-4eee-b5b1-d39bbafa338a">
<img width="1440" alt="Screenshot 2024-09-25 at 6 08 53 PM" src="https://github.com/user-attachments/assets/4db20c2a-f93a-446a-a37a-f81e252d8352">
