### ISSUE TITLE
<Icon> components  with different svg icons show up as the same icon.

### ISSUE THREAD

**Issue by gcosta0410** [natemoo-re/astro-icon#222]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v4.7.1
Node                     v20.12.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         astro-icon
```

### Describe the Bug

Using the package astro-icon, whenever I use 2 <Icon> components with **different** SVG icons, the second one will have the same icon as the first one.

### What's the expected result?

I expect both <Icon> components to have different icons.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tgmsd8?file=src%2Fpages%2Findex.astro

**Comment by osmfarid** [comment]
The issue you're encountering is likely due to SVGO's default optimization - `cleanupIds`, which after optimization set masks id to `a` for your icons.

https://svgo.dev/docs/plugins/cleanupIds/


You have two options:

1) Modify SVGO default behaviour via config for prevent id cleanup
2) Remove unnecessart groups and masks from your svgs


I have tried both methods, and they work
 
```ts
export default defineConfig({
  integrations: [icon({
    svgoOptions: {
      multipass: true,
      plugins: [
        {
          name: "cleanupIds",
          params: {
            minify: false,
          }
        }
      ]
    }
  })],
});
```
